#############################################################################
# Makefile for building: haven-wallet-gui
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  haven-wallet-gui.pro
# Template: app
# Command: C:/msys64/mingw32/Qt/bin/qmake.exe -o Makefile haven-wallet-gui.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:/msys64/mingw32/Qt/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: haven-wallet-gui.pro ../../../../mingw32/Qt/mkspecs/win32-g++/qmake.conf ../../../../mingw32/Qt/mkspecs/features/spec_pre.prf \
		../../../../mingw32/Qt/mkspecs/qdevice.pri \
		../../../../mingw32/Qt/mkspecs/features/device_config.prf \
		../../../../mingw32/Qt/mkspecs/common/angle.conf \
		../../../../mingw32/Qt/mkspecs/qconfig.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3drender.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axbase.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axserver.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_core.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_core_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_dbus.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_designer.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_gui.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_help.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_help_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_location.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_location_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_network.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_network_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_nfc.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_opengl.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_positioning.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qml.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quick.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_sensors.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_serialport.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_sql.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_svg.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_testlib.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_uitools.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_websockets.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_widgets.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_winextras.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_xml.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../mingw32/Qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../mingw32/Qt/mkspecs/features/qt_functions.prf \
		../../../../mingw32/Qt/mkspecs/features/qt_config.prf \
		../../../../mingw32/Qt/mkspecs/features/win32/qt_config.prf \
		../../../../mingw32/Qt/mkspecs/win32-g++/qmake.conf \
		../../../../mingw32/Qt/mkspecs/features/spec_post.prf \
		../../../../mingw32/Qt/mkspecs/features/exclusive_builds.prf \
		../../../../mingw32/Qt/mkspecs/features/toolchain.prf \
		../../../../mingw32/Qt/mkspecs/features/default_pre.prf \
		../../../../mingw32/Qt/mkspecs/features/win32/default_pre.prf \
		deployment.pri \
		../../../../mingw32/Qt/mkspecs/features/resolve_config.prf \
		../../../../mingw32/Qt/mkspecs/features/exclusive_builds_post.prf \
		../../../../mingw32/Qt/mkspecs/features/default_post.prf \
		../../../../mingw32/Qt/mkspecs/features/win32/rtti.prf \
		../../../../mingw32/Qt/mkspecs/features/precompile_header.prf \
		../../../../mingw32/Qt/mkspecs/features/warn_on.prf \
		../../../../mingw32/Qt/mkspecs/features/qt.prf \
		../../../../mingw32/Qt/mkspecs/features/resources.prf \
		../../../../mingw32/Qt/mkspecs/features/moc.prf \
		../../../../mingw32/Qt/mkspecs/features/win32/opengl.prf \
		../../../../mingw32/Qt/mkspecs/features/uic.prf \
		../../../../mingw32/Qt/mkspecs/features/file_copies.prf \
		../../../../mingw32/Qt/mkspecs/features/win32/windows.prf \
		../../../../mingw32/Qt/mkspecs/features/testcase_targets.prf \
		../../../../mingw32/Qt/mkspecs/features/exceptions.prf \
		../../../../mingw32/Qt/mkspecs/features/yacc.prf \
		../../../../mingw32/Qt/mkspecs/features/lex.prf \
		haven-wallet-gui.pro \
		../../../../mingw32/Qt/lib/qtmain.prl \
		../../../../mingw32/Qt/lib/Qt5Quick.prl \
		../../../../mingw32/Qt/lib/Qt5Widgets.prl \
		../../../../mingw32/Qt/lib/Qt5Gui.prl \
		../../../../mingw32/Qt/lib/Qt5Qml.prl \
		../../../../mingw32/Qt/lib/Qt5Network.prl \
		../../../../mingw32/Qt/lib/Qt5Core.prl
	$(QMAKE) -o Makefile haven-wallet-gui.pro
../../../../mingw32/Qt/mkspecs/features/spec_pre.prf:
../../../../mingw32/Qt/mkspecs/qdevice.pri:
../../../../mingw32/Qt/mkspecs/features/device_config.prf:
../../../../mingw32/Qt/mkspecs/common/angle.conf:
../../../../mingw32/Qt/mkspecs/qconfig.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dcore.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dextras.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dinput.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquick.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3drender.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axbase.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axserver.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_clucene_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_concurrent.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_core.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_core_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_dbus.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_designer.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_designer_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_gui.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_gui_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_help.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_help_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_location.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_location_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimedia.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_network.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_network_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_nfc.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_opengl.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_positioning.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_printsupport.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qml.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qml_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmltest.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quick.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quick_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_sensors.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_serialport.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_sql.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_sql_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_svg.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_svg_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_testlib.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_uitools.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_webchannel.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_websockets.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_widgets.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_winextras.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_xml.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_xml_private.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../mingw32/Qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../mingw32/Qt/mkspecs/features/qt_functions.prf:
../../../../mingw32/Qt/mkspecs/features/qt_config.prf:
../../../../mingw32/Qt/mkspecs/features/win32/qt_config.prf:
../../../../mingw32/Qt/mkspecs/win32-g++/qmake.conf:
../../../../mingw32/Qt/mkspecs/features/spec_post.prf:
../../../../mingw32/Qt/mkspecs/features/exclusive_builds.prf:
../../../../mingw32/Qt/mkspecs/features/toolchain.prf:
../../../../mingw32/Qt/mkspecs/features/default_pre.prf:
../../../../mingw32/Qt/mkspecs/features/win32/default_pre.prf:
deployment.pri:
../../../../mingw32/Qt/mkspecs/features/resolve_config.prf:
../../../../mingw32/Qt/mkspecs/features/exclusive_builds_post.prf:
../../../../mingw32/Qt/mkspecs/features/default_post.prf:
../../../../mingw32/Qt/mkspecs/features/win32/rtti.prf:
../../../../mingw32/Qt/mkspecs/features/precompile_header.prf:
../../../../mingw32/Qt/mkspecs/features/warn_on.prf:
../../../../mingw32/Qt/mkspecs/features/qt.prf:
../../../../mingw32/Qt/mkspecs/features/resources.prf:
../../../../mingw32/Qt/mkspecs/features/moc.prf:
../../../../mingw32/Qt/mkspecs/features/win32/opengl.prf:
../../../../mingw32/Qt/mkspecs/features/uic.prf:
../../../../mingw32/Qt/mkspecs/features/file_copies.prf:
../../../../mingw32/Qt/mkspecs/features/win32/windows.prf:
../../../../mingw32/Qt/mkspecs/features/testcase_targets.prf:
../../../../mingw32/Qt/mkspecs/features/exceptions.prf:
../../../../mingw32/Qt/mkspecs/features/yacc.prf:
../../../../mingw32/Qt/mkspecs/features/lex.prf:
haven-wallet-gui.pro:
../../../../mingw32/Qt/lib/qtmain.prl:
../../../../mingw32/Qt/lib/Qt5Quick.prl:
../../../../mingw32/Qt/lib/Qt5Widgets.prl:
../../../../mingw32/Qt/lib/Qt5Gui.prl:
../../../../mingw32/Qt/lib/Qt5Qml.prl:
../../../../mingw32/Qt/lib/Qt5Network.prl:
../../../../mingw32/Qt/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile haven-wallet-gui.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) -r C:/msys64/home/T440p/haven-gui-original/haven-gui/monero .qmake.stash

langupd:

deploy:
	windeployqt C:/msys64/home/T440p/haven-gui-original/haven-gui/release/bin/haven-wallet-gui.exe -release -qmldir=C:/msys64/home/T440p/haven-gui-original/haven-gui

deploy_win:

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
